champ_transl = {'АПЛ': 'premier-league',
                'Ла Лига': 'la-liga',
                'Серия А': 'seria-a',
                'Бундеслига': 'bundesliga'}

apl_transl = {'Арсенал': 'arsenal',
              'Челси': 'chelsea',
              'Манчестер Сити': 'manchester-city',
              'Ливерпуль': 'liverpool',
              'Борнмут': 'bournemouth',
              'Астон Вилла': 'aston-villa',
              'Брентфорд': 'brentford',
              'Кристал Пэлас': 'crystal-palace',
              'Эвертон': 'everton',
              'Фулхэм': 'fulham',
              'Ипсвич': 'ipswich-town',
              'Лестер': 'leicester',
              'Манчестер Юнайтед': 'mu',
              'Ньюкасл': 'newcastle',
              'Ноттенгем Форест': 'nottingham-forest',
              'Саутгемптон': 'southampton',
              'Тоттенхэм': 'tottenham',
              'Вест Хэм': 'west-ham',
              'Вулверхэмптон': 'wolves'}

la_liga_transl = {'Барселона': 'barcelona',
                  'Реал Мадрид': 'real',
                  'Валенсия': 'valencia',
                  'Осасуна': 'osasuna',
                  'Сельта': 'celta',
                  'Атлетик': 'athletic',
                  'Жирона': 'girona',
                  'Алавес': 'alaves',
                  'Атлетико': 'atletico',
                  'Эспаньол': 'espanyol',
                  'Хетафе': 'getafe',
                  'Лас-Пальмас': 'las-palmas',
                  'Леганес': 'leganes',
                  'Мальорка': 'mallorca',
                  'Райо Вальекано': 'rayo-vallecano',
                  'Бетис': 'betis',
                  'Реал Сосьедад': 'real-sociedad',
                  'Севилья': 'sevilla',
                  'Вильярреал': 'villareal',
                  'Вальядолид': 'valladolid'}

bundes_transl = {'Бавария': 'bayern',
                 'Боруссия Д': 'borussia',
                 'Байер': 'bayer',
                 'Штутгарт': 'stuttgart'}

seria_a_transl = {'Милан': 'milan',
                  'Интер': 'inter',
                  'Рома': 'roma',
                  'Ювентус': 'juventus'}
